export enum TypeKeys {
  GET_PROFILE_STARTED = "Profile.GET_PROFILE_STARTED",
  GET_PROFILE_SUCCESS = "Profile.GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILED = "Profile.GET_PROFILE_FAILED",

  RESET_PROFILE_STATE = "Profile.RESET_PROFILE_STATE",
}