export enum TypeKeys {
  AUTHENTICATION_LOGIN_STARTED = "Authentication.LOGIN_STARTED",
  AUTHENTICATION_LOGIN_SUCCESS = "Authentication.LOGIN_SUCCESS",
  AUTHENTICATION_LOGIN_FAILED = "Authentication.LOGIN_FAILED",
  AUTHENTICATION_SET_TOKEN = "Authentication.SET_TOKEN",

  AUTHENTICATION_RESET_STATE = "Authentication.RESET_STATE"
}