export enum TypeKeys {
  GET_EXAMS_STARTED = "Exams.GET_EXAMS_STARTED",
  GET_EXAMS_SUCCESS = "Exams.GET_EXAMS_SUCCESS",
  GET_EXAMS_FAILED = "Exams.GET_EXAMS_FAILED",
  
  RESET_EXAMS_STATE = "Exams.RESET_EXAMS_STATE"
}